sudo: required 
language: cpp
matrix:
  include:
    - os: linux
      env: DIST=ubuntu:18.04
      services: docker
    - os: linux
      env: DIST=ubuntu:19.04
      services: docker
    - os: linux
      env: DIST=fedora:30
      services: docker
    - os: linux
      env: DIST=fedora:31
      services: docker
    - os: linux
      env: DIST=archlinux:latest
      services: docker
script:
  - bash ./script.sh
